-- MySQL Script generated by MySQL Workbench
-- 11/18/15 12:10:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cakephpDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cakephpDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cakephpDB` DEFAULT CHARACTER SET utf8 ;
CREATE USER 'cakephpuser'@'localhost' identified by 'cakephppass';
GRANT ALL PRIVILEGES ON cakephpDB.* TO 'cakephpuser'@'localhost' WITH GRANT OPTION;

USE cakephpDB;

-- -----------------------------------------------------
-- Table `cakephpDB`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cakephpDB`.`Usuarios` (
  `login` VARCHAR(30) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `foto` VARCHAR(50) NULL DEFAULT './img_users/default.png',
  `idioma` VARCHAR(2) NULL DEFAULT 'es',
  PRIMARY KEY (`login`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cakephpDB`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cakephpDB`.`Categorias` (
  `nombreCategoria` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`nombreCategoria`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cakephpDB`.`Preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cakephpDB`.`Preguntas` (
  `idPregunta` INT NOT NULL AUTO_INCREMENT,
  `titulo` LONGTEXT NOT NULL,
  `cuerpo` LONGTEXT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `visto` INT NULL DEFAULT 0,
  `respuestas` INT NULL DEFAULT 0,
  `positivos` INT NULL DEFAULT 0,
  `negativos` INT NULL DEFAULT 0,
  `Usuarios_login` VARCHAR(30) NOT NULL,
  `Categorias_nombreCategoria` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idPregunta`, `Usuarios_login`, `Categorias_nombreCategoria`),
  INDEX `fk_Preguntas_Usuarios_idx` (`Usuarios_login` ASC),
  INDEX `fk_Preguntas_Categorias1_idx` (`Categorias_nombreCategoria` ASC),
  CONSTRAINT `fk_Preguntas_Usuarios`
    FOREIGN KEY (`Usuarios_login`)
    REFERENCES `cakephpDB`.`Usuarios` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Preguntas_Categorias1`
    FOREIGN KEY (`Categorias_nombreCategoria`)
    REFERENCES `cakephpDB`.`Categorias` (`nombreCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `cakephpDB`.`Respuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cakephpDB`.`Respuestas` (
  `idRespuesta` INT NOT NULL AUTO_INCREMENT,
  `cuerpoRes` LONGTEXT NOT NULL,
  `Usuarios_login` VARCHAR(30) NOT NULL,
  `Preguntas_idPregunta` INT NOT NULL,
  PRIMARY KEY (`idRespuesta`, `Usuarios_login`, `Preguntas_idPregunta`),
  INDEX `fk_Respuestas_Usuarios1_idx` (`Usuarios_login` ASC),
  INDEX `fk_Respuestas_Preguntas1_idx` (`Preguntas_idPregunta` ASC),
  CONSTRAINT `fk_Respuestas_Usuarios1`
    FOREIGN KEY (`Usuarios_login`)
    REFERENCES `cakephpDB`.`Usuarios` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Respuestas_Preguntas1`
    FOREIGN KEY (`Preguntas_idPregunta`)
    REFERENCES `cakephpDB`.`Preguntas` (`idPregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Insercion de datos en las tablas

INSERT INTO `Usuarios` (`login`, `nombre`, `foto`, `idioma`) VALUES
('Manolo', 'Manolo Perez', '', 'ES'),
('Juanito', 'Juan Sanchez', '', 'EN'),
('Carlito', 'Carlos Mendez', '', 'ES'),
('Marco', 'Marco Perez', '', 'ES'),
('Lucas', 'Lucas Rodriguez', '', 'EN');

INSERT INTO `Categorias` (`nombreCategoria`) VALUES
('Religion'),
('Electricidad'),
('Noticias');

INSERT INTO `Preguntas` (`idPregunta`, `titulo`, `cuerpo`, `fecha`, `visto`, `respuestas`, `positivos`, `negativos`, `Usuarios_login`, `Categorias_nombreCategoria`) VALUES
(0, '¿Si satanas castiga a los malos, eso no lo hace ser bueno?', 'Pues los malos se van al infierno y satanas les da su merecido, eso no lo hace bueno?', '22-10-2015', 16, 2, 16, 15, 'Manolo', 'Religion'),
(1, '¿A dónde va la luz cuando le doy al interruptor?', 'Simpre que le doy al interruptor para apagar la luz me pregunto a donde va, porque cuando le vuelvo a dar se vuelve a encender inmediatamente. Se queda esperando?', '18-10-2015', 124, 65, 32, 12, 'Juanito', 'Electricidad'),
(2, 'Carlinhos Brown perseguirá a los morosos tocando el tambor', 'Tras expirar su contrato con el correccional de Guantánamo, el cantante y percusionista Carlinhos Brown ha creado la empresa “Pe pe pe pepepe pe pe SL”, que ofrece un servicio de cobro de morosos.
El artista brasileño perseguirá a los deudores bailando al ritmo de una samba y tocando el tambor constantemente, una actividad que el cerebro humano no puede soportar más de dos horas seguidas, según los expertos.', '19-10-2015', 218, 48, 96, 3, 'Juanito', 'Noticias');

INSERT INTO `Respuestas` (`idRespuesta`, `cuerpoRes`, `Usuarios_login`, `Preguntas_idPregunta`) VALUES
(0, 'yo siempre dije q satanas era un buen loco incomprendido por esta sociedad posmoderna', 'Marco', 0),
(1, 'Tus premisas son acertadas pero como Satanas no existe eso no es valido', 'Lucas', 0);
