-- MySQL Script generated by MySQL Workbench
-- 11/18/15 12:10:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cakephpDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cakephpDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cakephpDB` DEFAULT CHARACTER SET utf8 ;
CREATE USER 'cakephpuser'@'localhost' identified by 'cakephppass';
GRANT ALL PRIVILEGES ON cakephpDB.* TO 'cakephpuser'@'localhost' WITH GRANT OPTION;

USE cakephpDB;

-- -----------------------------------------------------
-- Table `cakephpDB`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cakephpDB`.`Usuarios` (
  `login` VARCHAR(30) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `foto` VARCHAR(50) NULL DEFAULT './img_users/default.png',
  `idioma` VARCHAR(2) NULL DEFAULT 'es',
  PRIMARY KEY (`login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cakephpDB`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cakephpDB`.`Categorias` (
  `nombreCategorias` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`nombreCategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cakephpDB`.`Preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cakephpDB`.`Preguntas` (
  `idPregunta` INT NOT NULL AUTO_INCREMENT,
  `titulo` LONGTEXT NOT NULL,
  `cuerpo` LONGTEXT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `visto` INT NULL,
  `respuestas` INT NULL,
  `positivos` INT NULL,
  `negativos` INT NULL,
  `Usuarios_login` VARCHAR(30) NOT NULL,
  `Categorias_nombreCategorias` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idPregunta`, `Usuarios_login`, `Categorias_nombreCategorias`),
  INDEX `fk_Preguntas_Usuarios_idx` (`Usuarios_login` ASC),
  INDEX `fk_Preguntas_Categorias1_idx` (`Categorias_nombreCategorias` ASC),
  CONSTRAINT `fk_Preguntas_Usuarios`
    FOREIGN KEY (`Usuarios_login`)
    REFERENCES `cakephpDB`.`Usuarios` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Preguntas_Categorias1`
    FOREIGN KEY (`Categorias_nombreCategorias`)
    REFERENCES `cakephpDB`.`Categorias` (`nombreCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cakephpDB`.`Respuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cakephpDB`.`Respuestas` (
  `idRespuesta` INT NOT NULL AUTO_INCREMENT,
  `cuerpoRes` LONGTEXT NOT NULL,
  `Usuarios_login` VARCHAR(30) NOT NULL,
  `Preguntas_idPregunta` INT NOT NULL,
  PRIMARY KEY (`idRespuesta`, `Usuarios_login`, `Preguntas_idPregunta`),
  INDEX `fk_Respuestas_Usuarios1_idx` (`Usuarios_login` ASC),
  INDEX `fk_Respuestas_Preguntas1_idx` (`Preguntas_idPregunta` ASC),
  CONSTRAINT `fk_Respuestas_Usuarios1`
    FOREIGN KEY (`Usuarios_login`)
    REFERENCES `cakephpDB`.`Usuarios` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Respuestas_Preguntas1`
    FOREIGN KEY (`Preguntas_idPregunta`)
    REFERENCES `cakephpDB`.`Preguntas` (`idPregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
