-- MySQL Script generated by MySQL Workbench
-- 11/18/15 12:10:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema FAQ.life
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FAQ.life
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FAQ.life` DEFAULT CHARACTER SET utf8 ;
USE `FAQ.life` ;

-- -----------------------------------------------------
-- Table `FAQ.life`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FAQ.life`.`Usuario` (
  `login` VARCHAR(30) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `foto` VARCHAR(50) NULL DEFAULT './img_users/default.png',
  `idioma` VARCHAR(2) NULL DEFAULT 'es',
  PRIMARY KEY (`login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FAQ.life`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FAQ.life`.`Categorias` (
  `nombreCategorias` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`nombreCategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FAQ.life`.`Pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FAQ.life`.`Pregunta` (
  `idPregunta` INT NOT NULL AUTO_INCREMENT,
  `titulo` LONGTEXT NOT NULL,
  `cuerpo` LONGTEXT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `visto` INT NULL,
  `respuestas` INT NULL,
  `positivos` INT NULL,
  `negativos` INT NULL,
  `Usuario_login` VARCHAR(30) NOT NULL,
  `Categorias_nombreCategorias` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idPregunta`, `Usuario_login`, `Categorias_nombreCategorias`),
  INDEX `fk_Pregunta_Usuario_idx` (`Usuario_login` ASC),
  INDEX `fk_Pregunta_Categorias1_idx` (`Categorias_nombreCategorias` ASC),
  CONSTRAINT `fk_Pregunta_Usuario`
    FOREIGN KEY (`Usuario_login`)
    REFERENCES `FAQ.life`.`Usuario` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pregunta_Categorias1`
    FOREIGN KEY (`Categorias_nombreCategorias`)
    REFERENCES `FAQ.life`.`Categorias` (`nombreCategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FAQ.life`.`Respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FAQ.life`.`Respuesta` (
  `idRespuesta` INT NOT NULL AUTO_INCREMENT,
  `cuerpoRes` LONGTEXT NOT NULL,
  `Usuario_login` VARCHAR(30) NOT NULL,
  `Pregunta_idPregunta` INT NOT NULL,
  PRIMARY KEY (`idRespuesta`, `Usuario_login`, `Pregunta_idPregunta`),
  INDEX `fk_Respuesta_Usuario1_idx` (`Usuario_login` ASC),
  INDEX `fk_Respuesta_Pregunta1_idx` (`Pregunta_idPregunta` ASC),
  CONSTRAINT `fk_Respuesta_Usuario1`
    FOREIGN KEY (`Usuario_login`)
    REFERENCES `FAQ.life`.`Usuario` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Respuesta_Pregunta1`
    FOREIGN KEY (`Pregunta_idPregunta`)
    REFERENCES `FAQ.life`.`Pregunta` (`idPregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'faq_life' IDENTIFIED BY 'faq_lifepass';

GRANT SELECT ON TABLE `FAQ.life`.* TO 'faq_life';
GRANT SELECT, INSERT, TRIGGER ON TABLE `FAQ.life`.* TO 'faq_life';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `FAQ.life`.* TO 'faq_life';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
